### ISSUE TITLE
Sponsorsihp

### ISSUE THREAD

**Issue by KhalfaniW** [gajananpp/puppeteer-extension-transport#9]
@gajananpp

I wanted to message you that this is really awesom project. And has good documentation even with a working example 

So I am sending you $5. 

I don't know any other way to message other than making a temporary issue

**Comment by gajananpp** [comment]
Hi @KhalfaniW,

Thank you very much for your support. I have been not able to work on this project for almost 2 years now due to some personal reasons but soon I plan to complete the roadmap, update puppeteer dependency and add GPT provision to generate snippets.

Extremely happy you find this project useful. Thank you !!!
